export const TODOS_TYPES = {
  FETCH_TODOS_REQUEST: "FETCH_TODOS_REQUEST",
  SET_TODOS: "SET_TODOS",
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  EDIT_TODO: "EDIT_TODO",
  CLEAR_TODOS: "CLEAR_TODOS",
};